USER02 - Allow a User to register and login to the application
gdgpescara/hedwig pull request #169
Opened 2024-04-15 22:19 UTC by GiorgioCampea

Created the component LoginComponent to let the user signin or signup using Firebase-UI

The component is on the index page:
if the user is not logged:
![localhost_4321_ (2)](https://github.com/gdgpescara/hedwig/assets/15798771/792eae29-1438-4e60-a3b4-05c4e5dae27e)

if the user is logged:
![localhost_4321_ (4)](https://github.com/gdgpescara/hedwig/assets/15798771/d4933f13-9e47-43e8-851f-b82e4857930e)

There is a known issue for email provider for switching from signup to signin

https://github.com/firebase/firebaseui-web/issues/1040#issuecomment-1772045964

disable the email enumeration to make it work

2024-04-21 07:40 UTC, gregoriopalama requested changes

2024-04-21 07:40 UTC, gregoriopalama commented on src/components/LoginComponent.astro
> +      // Leave the lines as is for the providers you want to offer your users.
remove the comments

2024-04-21 07:40 UTC, gregoriopalama commented on src/components/LoginComponent.astro
> +      // https://github.com/firebase/firebaseui-web/issues/1040
remove these comments

2024-04-21 07:40 UTC, gregoriopalama commented on src/components/LoginComponent.astro
> +    tosUrl: "<your-tos-url>",
remove the comments and add a tos url. I would add a very simple page, for now, with just a "Terms of service". we will add an issue to work on it

2024-04-21 07:40 UTC, gregoriopalama commented on src/components/LoginComponent.astro
> +      window.location.assign("<your-privacy-policy-url>");
same for the tos url

2024-04-21 07:40 UTC, gregoriopalama commented on src/components/LoginComponent.astro
> +        return console.error(error);
remove the comments

2024-04-21 12:13 UTC, GiorgioCampea commented
some important comment, useful for documentation:

- in order to make the switch from signin to signup for email remember to disable the the email enumeration protection [see this github issue](https://github.com/firebase/firebaseui-web/issues/1040)
- all the javascript in astro is bundled, so we need to check if the starting div is present [see this github issue](https://github.com/withastro/astro/issues/5739)

2024-04-22 10:50 UTC, irsooti commented
I would like to remark that firebase-ui comes with a [stylesheet](https://github.com/firebase/firebaseui-web/blob/master/stylesheet/firebase-ui.css)which doesn't stick on our style guide - _At this point, we are in a hurry, and could skip this aspect for now._

An upcoming enhancement could involve customizing buttons and fonts according to our style guide, as opposed to using the default firebase-ui design.

2024-04-22 10:58 UTC, gregoriopalama commented
> I would like to remark that firebase-ui comes with a [stylesheet](https://github.com/firebase/firebaseui-web/blob/master/stylesheet/firebase-ui.css)which doesn't stick on our style guide - _At this point, we are in a hurry, and could skip this aspect for now._
> 
> An upcoming enhancement could involve customizing buttons and fonts according to our style guide, as opposed to using the default firebase-ui design.

I totally agree on this.
It's not just that we are in a hurry. Other issues need this functionality, so the quickest and dirtiest way sounds good for us, for now. 
When we will work on the public UI, we will surely have to fix this

2024-04-23 08:01 UTC, gregoriopalama approved these changes

2024-04-23 11:13 UTC, irsooti approved these changes

2024-04-24 21:47 UTC, merged