BO01 - Create a layout for the BackOffice
gdgpescara/hedwig pull request #170
Opened 2024-04-16 13:50 UTC by valekuro

Created Layout component, Header component and Sidebar component.

**_The issue is not completed!!_**

This PR is submitted for showing work in progress purposes.
Actual bug:
  - Ipad Mini e Ipad Air in landscape the drawer not working well
  - In desktop mode the menu is not in overlay
  - I used letters instead of icons because I don't know if we want to use fontawesome or custom icons

2024-04-16 15:56 UTC, gregoriopalama requested changes

2024-04-16 15:56 UTC, gregoriopalama commented on src/feature-header/Header.tsx
Can you please make this an Astro component? It will be used site-wide and it is a simple component, so it would be preferable to stick to the base framework.

2024-04-16 15:56 UTC, gregoriopalama commented on src/feature-sidebar/Sidebar.tsx
Same as for the header. Can you make this an Astro component?

2024-04-16 15:56 UTC, gregoriopalama commented on src/feature-sidebar/SidebarItems.tsx
Can you make this an Astro component?

2024-04-16 15:56 UTC, gregoriopalama commented on src/feature-sidebar/SidebarItems.tsx
> +            {items.map((item:ISidebarItems)=><li key={item.item || item.icon}><div className="flex flex-row gap-5"><p onClick={()=>console.log('ciao')}>{item.icon}</p><a href={item.url}>{item.item}</
this should navigate to the given url

2024-04-16 15:56 UTC, gregoriopalama commented on src/layouts/Layout.astro
Rename this to BackOfficeLayout

2024-04-16 15:56 UTC, gregoriopalama commented on src/pages/index.astro
Please, revert changes to this file. This will be the public homepage. In BO02 we will create the page, that will use the BackOfficeLayout

2024-04-17 08:33 UTC, irsooti commented on src/feature-sidebar/ISidebar.ts
I would suggest to co-locate types to its component, to avoid too much fragmentation of files.
Also, I suggest to remove the prefix `feature-x`, maybe documentation is misleading but for `feature-x` is meant to the name of the feature itself. 
In other words, `feature-sidebar` should be renamed in `backoffice-sidebar` to make it clear who it belongs to (same for header and layouts).

What do you think? cc @gregoriopalama

2024-05-02 08:34 UTC, irsooti commented
Hi @valekuro, thanks for the contribution!
I'd advise just one minor adjustment.

You have created 3 folders: backoffice-sidebar, backoffice-header, backoffice-layout. 
We could condense all 3 domains to just one: backoffice-layout. 

The reason is: backoffice-header and backoffice-sidebar alone are useless, they are atoms that compose an organism, the layout. So my suggestion is to move header and sidebar inside backoffice-layout to avoid too much fragmentation.

2024-05-12 15:50 UTC, valekuro commented
PR ready! @gregoriopalama @irsooti 
I used Iconify and astro-icon. 
To choose icons visit: [Icon-sets](https://icon-sets.iconify.design/) and choose "Material Design Icon".

2024-05-20 14:42 UTC, gregoriopalama requested changes

2024-05-20 14:42 UTC, gregoriopalama commented on src/pages/index.astro
Please, reset this to the version that is actually on main

2024-05-22 14:33 UTC, merged